// kernel_tdp_probe_boot.c — specialized boot for the T-Deck Plus hardware probe
//
// This is PURR OS brought up to the point where the kernel is alive and the
// hardware is reachable, and then deliberately stopped: no display driver, no
// touch, no UI backend, no module loader, no apps. What runs instead is a
// command loop on the native USB port that lets a host drive the chip's
// peripherals directly and read back what they return.
//
// It exists for the emulator work. A capture of every register the real
// firmware WRITES is already obtainable by instrumenting the driver; what
// cannot be obtained that way is what the silicon READS BACK — whether CMD.USR
// self-clears, what MISO yields with nothing on the bus, how many cycles pass
// before TRANS_DONE asserts. Those are the values an emulator author would
// otherwise have to guess, and a wrong guess shows up as a hang rather than as
// a visible error. So this kernel makes the read side interrogable from a host
// script, one register at a time.
//
// SAFETY. Every host-supplied address goes through purr_probe_guard.c, which is
// allowlist-first and additionally refuses a fixed set of irreversible or
// security-critical blocks outright. eFuse is the reason that file exists:
// eFuse bits burn one way, and a stray word into the programming registers can
// permanently enable flash encryption or secure boot, or blow the JTAG and
// download-mode disable bits, turning a development board into one that can
// never be reflashed or debugged again. This kernel cannot address that block
// at all, for reads or writes, and there is no runtime or compile-time switch
// that changes it. The gate is proven at boot by probe_guard_selftest() and the
// command loop refuses to serve anything if that proof fails.
//
// Deliberately NOT started here:
//   - the module loader          (nothing to load; no UI in this build)
//   - purr_crash_guard strikes   (a debug tool that disables itself after a
//                                 few crashes is worse than useless — the
//                                 whole point is to survive poking at things
//                                 until they break)
//   - WiFi / BT / LoRa           (radios contend for the SPI bus under study)

#include "purr_kernel.h"
#include "purr_probe_guard.h"
#include "purr_probe_cmd.h"

#include "esp_log.h"
#include "esp_system.h"
#include "esp_heap_caps.h"
#include "nvs_flash.h"
#include "freertos/FreeRTOS.h"
#include "freertos/task.h"

static const char *TAG = "tdp_probe";

void app_main(void)
{
    ESP_LOGI(TAG, "PURR OS %s — hardware probe kernel (no UI)", PURR_KERNEL_VERSION);

    // NVS only. No SPIFFS, no SD: both would put the flash controller and the
    // SD card on the very SPI bus this tool exists to observe, and a background
    // filesystem flush landing in the middle of a captured trace is exactly the
    // kind of noise that makes a capture unreproducible.
    esp_err_t nvs_ret = nvs_flash_init();
    if (nvs_ret == ESP_ERR_NVS_NO_FREE_PAGES || nvs_ret == ESP_ERR_NVS_NEW_VERSION_FOUND) {
        nvs_flash_erase();
        nvs_flash_init();
    }

    // Board power rails, generated by purrstrap from device.pcat. Runs before
    // anything tries to talk to a peripheral — on boards with a gated rail,
    // skipping it means every subsequent access "succeeds" against an
    // unpowered, floating bus and reads back garbage that looks like data.
    extern void purr_device_init(void);
    purr_device_init();

    // ── Arm the access gate ──────────────────────────────────────────────────
    //
    // Before this returns true, every accessor in purr_probe_guard.c refuses
    // everything. It is therefore impossible for the command loop to serve a
    // single read or write on a build where the deny list has been broken —
    // which is the property that makes the eFuse protection load-bearing rather
    // than a comment someone can quietly invalidate later.
    if (!probe_guard_selftest()) {
        ESP_LOGE(TAG, "==================================================");
        ESP_LOGE(TAG, " ACCESS GATE SELFTEST FAILED");
        ESP_LOGE(TAG, " The MMIO allow/deny tables are inconsistent.");
        ESP_LOGE(TAG, " Refusing to serve commands. Fix purr_probe_guard.c.");
        ESP_LOGE(TAG, "==================================================");
        // Falls through on purpose: probe_cmd_loop() detects the unarmed gate
        // and answers every request with a refusal forever, which is far easier
        // to diagnose from the host than a device that simply went silent.
    } else {
        ESP_LOGI(TAG, "eFuse / flash-encryption / secure-boot registers: BLOCKED");
    }

    ESP_LOGI(TAG, "internal free %u, spiram free %u",
             (unsigned)heap_caps_get_free_size(MALLOC_CAP_INTERNAL),
             (unsigned)heap_caps_get_free_size(MALLOC_CAP_SPIRAM));

    // Nothing above registered a display catcall, so anything that waits on
    // boot-ready would wait forever. Set it so a stray module — should one ever
    // be added to this device — does not deadlock.
    purr_kernel_set_boot_ready(true);

    ESP_LOGI(TAG, "probe ready — driving command loop on native USB");

    // Never returns.
    probe_cmd_loop();
}
