// mochi_springboard.c — the iOS-style home screen.
//
// ── Layout, and why it is what it is ────────────────────────────────────────
// iOS is a portrait design; the T-Deck Plus is 320x240 landscape. Everything
// below is derived from the real panel size rather than hardcoded, so a
// differently-sized LVGL device still lays out sanely.
//
//   ┌────────────────────────────────────────┐
//   │ status bar (systemui, lv_layer_top)    │  PURR_SYSTEMUI_STATUS_H
//   │                                        │
//   │    ▢      ▢      ▢      ▢              │  page grid: squircle + label,
//   │   Term   Set    File   Calc            │  s_cols x s_rows
//   │                                        │
//   │    ▢      ▢      ▢      ▢              │
//   │   Msn    Mesh   Drv    Milk            │
//   │                                        │
//   │                • ○                     │  page dots
//   │  ╭──────────────────────────────────╮  │
//   │  │    ▢      ▢      ▢      ▢        │  │  dock (translucent, rounded)
//   │  ╰──────────────────────────────────╯  │
//   │              ▂▂▂▂▂▂▂▂                  │  home indicator (on layer_top,
//   └────────────────────────────────────────┘  so it persists over apps)
//
// Grid columns deliberately equal s_dock_slots so the two line up vertically —
// see s_cols below for why that matters to cursor movement, not just looks.
//
// The dock holds the first s_dock_slots apps in registry order — there is no
// separate favourites concept in app_manager yet, and inventing one here would
// be state this backend has no business owning. Those apps deliberately still
// appear in the grid too: hiding them would make the grid's contents depend on
// the dock's size, which is surprising when the registry changes.
//
// ── Selection model ─────────────────────────────────────────────────────────
// A single cursor spans grid and dock as one addressable space: indices
// [0, page_capacity) are grid cells on the current page, and the dock occupies
// the indices immediately after. Down from the bottom grid row enters the dock;
// up from the dock returns to the row above. That keeps trackball navigation a
// single continuous motion instead of two disconnected zones.

#include "mochi.h"
#include "../systemui/systemui.h"
#include "../../assets/icons/blackpurr_icons.h"
#include "../../kernel/core/purr_kernel.h"
#include "../../kernel/catcalls/purr_win.h"
#include "../app_manager/app_manager.h"
#include "esp_log.h"
#include <stdio.h>
#include <string.h>
#include <ctype.h>

// Built-in wallpaper, generated by source/assets/wallpapers/convert_wallpaper.py
// (--c-array) and compiled in via this component's CMakeLists. Declared here
// rather than in a header because it is one symbol with exactly one consumer.
extern const lv_img_dsc_t purr_wallpaper;

// systemui host hook — the lock screen draws the same wallpaper the
// springboard does. Always available here, since it is compiled in.
static const lv_img_dsc_t *mochi_wallpaper(void) { return &purr_wallpaper; }

static const char *TAG = "mochi_sb";

// ── iOS system palette ──────────────────────────────────────────────────────
// Values are Apple's own light-mode system colours, which is most of what
// makes a UI read as "iOS" before any layout is considered.
#define COL_BG          lv_color_hex(0xF2F2F7)  // systemGroupedBackground
#define COL_PANEL       lv_color_hex(0xFFFFFF)  // secondarySystemGroupedBackground
#define COL_ACCENT      lv_color_hex(0x007AFF)  // systemBlue
#define COL_LABEL       lv_color_hex(0x1C1C1E)  // label
#define COL_LABEL_2     lv_color_hex(0x8E8E93)  // secondaryLabel / systemGray
#define COL_DOT_ON      lv_color_hex(0x3C3C43)
#define COL_DOT_OFF     lv_color_hex(0xC7C7CC)
#define COL_INDICATOR   lv_color_hex(0x1C1C1E)

// Grid shape is DERIVED FROM THE PANEL at runtime, not fixed.
//
// Mochi was written against the T-Deck Plus's 320x240 and hard-coded 4x2. On
// the Tab5 (640x360 as PURR sees it - the ST7123 driver renders half-size and
// lets the PPA scale 2x during its rotate pass) that same 4x2 would show 8 apps
// on a screen with room for about 24, with enormous dead space between them.
//
// The iOS behaviour being copied is: icons stay the SAME PHYSICAL SIZE and a
// bigger screen simply holds MORE of them. So ICON_SIZE stays constant and the
// column/row counts scale instead. Cupcake gets this for free from
// LV_FLEX_FLOW_ROW_WRAP; Mochi positions absolutely (it needs stable cell
// coordinates for paging and the trackball cursor), so it computes the counts.
//
// Column target reproduces the original 4 columns at 320px (320/80).
//
// The ROW divisor is deliberately derived from what a cell must actually
// CONTAIN rather than picked to hit a number: an icon, its caption, and a few
// pixels of separation. Sizing it by content means the grid claims a row only
// when it can genuinely draw one.
//
// This was first written as a guessed 67, which produced 4x1 on the T-Deck Plus
// instead of 4x2 — its usable grid band is 132px, and 132/67 floors to 1. Two
// pixels of estimation error silently halved the home screen. The value below
// cannot drift that way, because it is the same constants the cell is built
// from: 132/64 = 2 rows here, and Tab5's ~254px band gives 3.
#define CELL_W_TARGET   80
#define CELL_H_MIN      (ICON_SIZE + LABEL_H + 4)

// Array bounds. Generous enough for any panel this OS runs on, and the runtime
// counts are clamped to them - a larger display gets a full grid rather than
// overflowing one.
#define MAX_COLS        8
#define MAX_ROWS        4
#define MAX_DOCK        6
#define MAX_PAGE_CAP    (MAX_COLS * MAX_ROWS)
#define MAX_APPS        64

// Live values, set by compute_metrics() before anything is laid out. Defaults
// match the original constants so a device whose get_info() fails still builds
// the T-Deck Plus layout rather than a degenerate one.
static int s_cols        = 4;
static int s_rows        = 2;
static int s_dock_slots  = 4;
static int s_page_cap    = 8;

#define ICON_SIZE       46
#define ICON_RADIUS     12   // ~26% of size — approximates iOS's superellipse
#define DOCK_ICON_SIZE  38
#define DOCK_ICON_RADIUS 10
#define LABEL_H         14
#define DOT_SIZE         6


// ── State ───────────────────────────────────────────────────────────────────

static int s_page       = 0;   // current grid page
static int s_page_count = 1;
static int s_sel        = 0;   // cursor: [0,s_page_cap) = grid, then dock slots
static int s_app_count  = 0;
static int s_last_app_count = -1;

static lv_obj_t *s_screen;
static lv_obj_t *s_grid_cells[MAX_PAGE_CAP];   // squircle objects, NULL if empty
static lv_obj_t *s_dock_cells[MAX_DOCK];
static lv_obj_t *s_dots[8];
static int       s_dot_count = 0;

// Registry index backing each visible cell, -1 when the cell is empty.
static int s_grid_app[MAX_PAGE_CAP];
static int s_dock_app[MAX_DOCK];

// Whether the selection ring is drawn. Touch is a direct pointing device — iOS
// has no cursor, and showing one while someone is tapping icons is just noise —
// so the ring is hidden the moment touch is used and returns the moment the
// trackball or keyboard moves the cursor. The selected index keeps tracking
// underneath either way, so switching back resumes where it actually is.
// Declared here rather than beside the touch handlers because render_selection()
// (much further up) is its main reader.
static bool s_cursor_visible = false;

// Cursor indices past s_page_cap address the dock.
#define SEL_IS_DOCK(s)  ((s) >= s_page_cap)
#define SEL_DOCK_SLOT(s) ((s) - s_page_cap)

// Defined with the input handlers further down, but every icon gets them at
// build time — see sb_touch_cb for why a swipe has to be caught on the icons
// and not only on the background.
static void attach_touch_handlers(lv_obj_t *obj);

static uint32_t hash_str(const char *s)
{
    uint32_t h = 2166136261u; // FNV-1a
    while (*s) { h ^= (uint8_t)*s++; h *= 16777619u; }
    return h;
}

// Deterministic per-app icon colour, drawn from an iOS-ish saturated set
// rather than a free hash-to-RGB — arbitrary hashed colours produce muddy
// mid-tones that look nothing like a real springboard, where every icon is a
// confident saturated hue.
lv_color_t mochi_color_for_app(const char *name)
{
    static const uint32_t palette[] = {
        0x007AFF, // blue
        0x34C759, // green
        0xFF9500, // orange
        0xFF3B30, // red
        0xAF52DE, // purple
        0x5AC8FA, // teal
        0xFFCC00, // yellow
        0xFF2D55, // pink
        0x5856D6, // indigo
    };
    return lv_color_hex(palette[hash_str(name) % (sizeof(palette) / sizeof(palette[0]))]);
}

// The system icon set — see mochi.h for why the launcher owns it. Covers every
// app currently in the registry; anything unmatched gets the generic tool
// glyph rather than nothing, so a newly-dropped .meow/.hiss app still renders
// a real icon on its first launch instead of an empty square.
const lv_img_dsc_t *mochi_icon_for_app(const char *name)
{
    static const struct { const char *app_name; const lv_img_dsc_t *icon; } map[] = {
        { "settings",   &bp_icon_settings_48   },
        { "about",      &bp_icon_about_48      },
        { "terminal",   &bp_icon_terminal_48   },
        { "fileman",    &bp_icon_fileman_48    },
        { "calculator", &bp_icon_calculator_48 },
        { "hwtest",     &bp_icon_hwtest_48     },
        { "drivermgr",  &bp_icon_drivermgr_48  },
        { "milkbar",    &bp_icon_milkbar_48    },
        { "nearby",     &bp_icon_nearby_48     },
        { "services",   &bp_icon_services_48   },
        { "taskmgr",    &bp_icon_taskmgr_48    },
        { "meshdiag",   &bp_icon_meshdiag_48   },
        { "msn",        &bp_icon_msn_48        },
        { "meshchat",   &bp_icon_messages_48   },
        { "magicmac",   &bp_icon_magicmac_48   },
        { "magidos",    &bp_icon_magidos_48    },
    };
    if (!name) return &bp_icon_tools_48;
    for (size_t i = 0; i < sizeof(map) / sizeof(map[0]); i++) {
        if (strcmp(name, map[i].app_name) == 0) return map[i].icon;
    }
    return &bp_icon_tools_48;
}

// ── Geometry, derived from the real panel ───────────────────────────────────

typedef struct {
    lv_coord_t grid_y, grid_h;
    lv_coord_t cell_w, cell_h;
    lv_coord_t dots_y;
    lv_coord_t dock_y, dock_h;
    lv_coord_t indicator_y;
} sb_metrics_t;

static sb_metrics_t s_m;

static void compute_metrics(uint16_t w, uint16_t h)
{
    const lv_coord_t top = PURR_SYSTEMUI_STATUS_H;

    s_m.indicator_y = (lv_coord_t)(h - 8);
    s_m.dock_h      = DOCK_ICON_SIZE + 12;
    s_m.dock_y      = (lv_coord_t)(s_m.indicator_y - 6 - s_m.dock_h);
    s_m.dots_y      = (lv_coord_t)(s_m.dock_y - 12);

    s_m.grid_y = (lv_coord_t)(top + 6);
    s_m.grid_h = (lv_coord_t)(s_m.dots_y - 4 - s_m.grid_y);

    // Grid shape first — cell sizes depend on it.
    //
    // Columns come from width, rows from the grid band that is actually left
    // after the status bar, page dots, dock and home indicator have taken
    // theirs. Deriving rows from grid_h rather than from screen height is what
    // stops a tall-but-cramped panel from claiming a row it cannot draw.
    s_cols = (int)(w / CELL_W_TARGET);
    if (s_cols < 1)         s_cols = 1;
    if (s_cols > MAX_COLS)  s_cols = MAX_COLS;

    s_rows = (int)(s_m.grid_h / CELL_H_MIN);
    if (s_rows < 1)         s_rows = 1;
    if (s_rows > MAX_ROWS)  s_rows = MAX_ROWS;

    // The dock tracks the columns so the two stay vertically aligned, which is
    // what makes move_cursor()'s grid<->dock step a straight 1:1 column mapping
    // instead of an approximation. Capped at MAX_DOCK because a dock spanning
    // eight slots stops reading as a dock — past that the cursor code's
    // existing clamp handles the mismatch (it already did, since a partially
    // populated dock has always been possible).
    s_dock_slots = s_cols < MAX_DOCK ? s_cols : MAX_DOCK;

    s_page_cap = s_cols * s_rows;

    s_m.cell_w = (lv_coord_t)(w / s_cols);
    s_m.cell_h = (lv_coord_t)(s_m.grid_h / s_rows);

    ESP_LOGI(TAG, "grid %dx%d (%d/page), dock %d, cell %dx%d on %ux%u",
             s_cols, s_rows, s_page_cap, s_dock_slots,
             (int)s_m.cell_w, (int)s_m.cell_h, w, h);
}

// ── Data ────────────────────────────────────────────────────────────────────

static void recompute_pages(void)
{
    s_app_count  = app_manager_count();
    if (s_app_count > MAX_APPS) s_app_count = MAX_APPS;
    s_page_count = (s_app_count + s_page_cap - 1) / s_page_cap;
    if (s_page_count < 1) s_page_count = 1;
    if (s_page >= s_page_count) s_page = s_page_count - 1;
}

// ── Rendering ───────────────────────────────────────────────────────────────

static void cell_click_cb(lv_event_t *e);
static void launch_app(int registry_idx);

// The focus ring: an iOS-style selection cue that doesn't disturb layout —
// drawn as an outline on the squircle rather than a border, so the icon's own
// size never changes and the grid can't reflow as the cursor moves.
static void apply_selection_style(lv_obj_t *obj, bool selected)
{
    if (!obj) return;
    lv_obj_set_style_outline_width(obj, selected ? 3 : 0, 0);
    lv_obj_set_style_outline_color(obj, COL_ACCENT, 0);
    lv_obj_set_style_outline_pad(obj, selected ? 3 : 0, 0);
    lv_obj_set_style_outline_opa(obj, selected ? LV_OPA_COVER : LV_OPA_TRANSP, 0);
}

static void render_selection(void)
{
    // s_cursor_visible false => no ring anywhere, which is the touch-driven
    // state. The selected index is still tracked underneath so switching back
    // to the trackball resumes from where the cursor actually is.
    for (int i = 0; i < s_page_cap; i++) {
        apply_selection_style(s_grid_cells[i],
            s_cursor_visible && !SEL_IS_DOCK(s_sel) && i == s_sel);
    }
    for (int i = 0; i < s_dock_slots; i++) {
        apply_selection_style(s_dock_cells[i],
            s_cursor_visible && SEL_IS_DOCK(s_sel) && i == SEL_DOCK_SLOT(s_sel));
    }
}

// Builds one squircle icon + caption. Returns the squircle so the caller can
// track it for selection styling.
static lv_obj_t *build_icon(lv_obj_t *parent, int registry_idx,
                             lv_coord_t x, lv_coord_t y,
                             lv_coord_t size, lv_coord_t radius,
                             bool with_label, int sel_index)
{
    const app_entry_t *app = app_manager_get(registry_idx);
    if (!app) return NULL;

    lv_obj_t *sq = lv_obj_create(parent);
    lv_obj_remove_style_all(sq);
    lv_obj_set_size(sq, size, size);
    lv_obj_set_pos(sq, x, y);
    purr_fx_radius(sq, radius);
    lv_obj_set_style_bg_color(sq, mochi_color_for_app(app->name), 0);
    lv_obj_set_style_bg_opa(sq, LV_OPA_COVER, 0);
    lv_obj_clear_flag(sq, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(sq, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(sq, cell_click_cb, LV_EVENT_CLICKED, (void *)(intptr_t)sel_index);
    attach_touch_handlers(sq);   // a swipe usually starts on an icon, not bare background

    // White Ionicon centred on the tint — the iOS app-icon construction. The
    // source assets are 48px and lv_img_set_zoom() takes 256 = 100%, so scale
    // the glyph to a bit over half the squircle: too large and it crowds the
    // corner radius, too small and it floats.
    lv_obj_t *glyph = lv_img_create(sq);
    lv_img_set_src(glyph, mochi_icon_for_app(app->name));
    lv_img_set_zoom(glyph, (uint16_t)(((size * 55 / 100) * 256) / 48));
    lv_obj_center(glyph);
    lv_obj_clear_flag(glyph, LV_OBJ_FLAG_CLICKABLE);

    // A running app gets a small dot under its icon, the way iOS marks
    // recently-used apps in the dock.
    if (app->state == APP_STATE_RUNNING) {
        lv_obj_t *dot = lv_obj_create(parent);
        lv_obj_remove_style_all(dot);
        lv_obj_set_size(dot, 4, 4);
        purr_fx_radius(dot, LV_RADIUS_CIRCLE);
        lv_obj_set_style_bg_color(dot, COL_LABEL_2, 0);
        lv_obj_set_style_bg_opa(dot, LV_OPA_COVER, 0);
        lv_obj_set_pos(dot, (lv_coord_t)(x + size / 2 - 2), (lv_coord_t)(y + size + 1));
        lv_obj_clear_flag(dot, LV_OBJ_FLAG_CLICKABLE);
    }

    if (with_label) {
        lv_obj_t *lbl = lv_label_create(parent);
        lv_label_set_text(lbl, app->name);
        lv_label_set_long_mode(lbl, LV_LABEL_LONG_DOT);
        lv_obj_set_width(lbl, (lv_coord_t)(s_m.cell_w - 4));
        lv_obj_set_style_text_align(lbl, LV_TEXT_ALIGN_CENTER, 0);
        lv_obj_set_style_text_color(lbl, COL_LABEL, 0);
        lv_obj_set_style_text_font(lbl, &lv_font_montserrat_14, 0);
        lv_obj_set_pos(lbl, (lv_coord_t)(x + size / 2 - (s_m.cell_w - 4) / 2),
                             (lv_coord_t)(y + size + 4));
        lv_obj_clear_flag(lbl, LV_OBJ_FLAG_CLICKABLE);
    }
    return sq;
}

static void render_dots(void)
{
    for (int i = 0; i < s_dot_count; i++) {
        if (!s_dots[i]) continue;
        bool on = (i == s_page);
        lv_obj_set_style_bg_color(s_dots[i], on ? COL_DOT_ON : COL_DOT_OFF, 0);
        // _keep, not the accent variant: the inactive dot's translucency is how
        // "which page am I on" is communicated. Flooding it with accent would
        // make both states identical. Opaque-at-own-colour still distinguishes
        // them via COL_DOT_ON/COL_DOT_OFF.
        purr_systemui_fx_bg_opa_keep(s_dots[i], on ? LV_OPA_COVER : LV_OPA_50);
    }
}

// Rebuilds the whole springboard. Only called on page change or registry
// change — never per tick.
static void render_all(void)
{
    if (!s_screen) return;
    lv_obj_clean(s_screen);

    // Wallpaper: compiled into the firmware rather than loaded from SPIFFS or
    // SD (see source/assets/wallpapers/convert_wallpaper.py's convert_c()).
    // A built-in image is the only kind guaranteed to exist on a freshly-erased
    // device with no card inserted — exactly the state a *default* wallpaper
    // has to survive. Runtime-selectable wallpapers stay a separate, additive
    // path.
    //
    // Recreated here rather than once at init because this function cleans the
    // whole screen on every page change. That is cheap: lv_img references the
    // const descriptor, it does not copy the 150KB of pixel data.
    //
    // First child, so every icon, dot, dock and label added below paints on
    // top; and non-clickable, so it never swallows a tap or the swipe handlers
    // attached to the root.
    lv_obj_t *bg = lv_img_create(s_screen);
    lv_img_set_src(bg, &purr_wallpaper);
    lv_obj_set_pos(bg, 0, 0);
    lv_obj_clear_flag(bg, LV_OBJ_FLAG_CLICKABLE);

    memset(s_grid_cells, 0, sizeof(s_grid_cells));
    memset(s_dock_cells, 0, sizeof(s_dock_cells));
    memset(s_dots, 0, sizeof(s_dots));
    s_dot_count = 0;
    for (int i = 0; i < s_page_cap;    i++) s_grid_app[i] = -1;
    for (int i = 0; i < s_dock_slots;  i++) s_dock_app[i] = -1;

    uint16_t w = mochi_hal_width();

    // ── Grid ────────────────────────────────────────────────────────────────
    int base = s_page * s_page_cap;
    for (int cell = 0; cell < s_page_cap; cell++) {
        int idx = base + cell;
        if (idx >= s_app_count) break;
        int col = cell % s_cols;
        int row = cell / s_cols;
        lv_coord_t cx = (lv_coord_t)(col * s_m.cell_w + (s_m.cell_w - ICON_SIZE) / 2);
        lv_coord_t cy = (lv_coord_t)(s_m.grid_y + row * s_m.cell_h);
        s_grid_cells[cell] = build_icon(s_screen, idx, cx, cy,
                                         ICON_SIZE, ICON_RADIUS, true, cell);
        s_grid_app[cell] = idx;
    }

    // ── Page dots ───────────────────────────────────────────────────────────
    if (s_page_count > 1) {
        int n = s_page_count > 8 ? 8 : s_page_count;
        lv_coord_t total = (lv_coord_t)(n * DOT_SIZE + (n - 1) * 6);
        lv_coord_t dx = (lv_coord_t)((w - total) / 2);
        for (int i = 0; i < n; i++) {
            lv_obj_t *d = lv_obj_create(s_screen);
            lv_obj_remove_style_all(d);
            lv_obj_set_size(d, DOT_SIZE, DOT_SIZE);
            purr_fx_radius(d, LV_RADIUS_CIRCLE);
            lv_obj_set_pos(d, dx, s_m.dots_y);
            lv_obj_clear_flag(d, LV_OBJ_FLAG_CLICKABLE);
            s_dots[i] = d;
            dx = (lv_coord_t)(dx + DOT_SIZE + 6);
        }
        s_dot_count = n;
        render_dots();
    }

    // ── Dock ────────────────────────────────────────────────────────────────
    int dock_n = s_app_count < s_dock_slots ? s_app_count : s_dock_slots;
    if (dock_n > 0) {
        lv_coord_t dock_w = (lv_coord_t)(w - 24);
        lv_obj_t *dock = lv_obj_create(s_screen);
        lv_obj_remove_style_all(dock);
        lv_obj_set_size(dock, dock_w, s_m.dock_h);
        lv_obj_set_pos(dock, 12, s_m.dock_y);
        purr_fx_radius(dock, 16);
        lv_obj_set_style_bg_color(dock, COL_PANEL, 0);
        // Translucent rather than solid: iOS's dock is a blur over the
        // wallpaper. Real blur is far too expensive per frame here, but
        // partial opacity over the ground colour reads the same way at this
        // size and costs nothing.
        purr_systemui_fx_bg_opa(dock, LV_OPA_60);
        lv_obj_clear_flag(dock, LV_OBJ_FLAG_SCROLLABLE);
        lv_obj_clear_flag(dock, LV_OBJ_FLAG_CLICKABLE);

        lv_coord_t slot_w = (lv_coord_t)(dock_w / dock_n);
        for (int i = 0; i < dock_n; i++) {
            lv_coord_t ix = (lv_coord_t)(12 + i * slot_w + (slot_w - DOCK_ICON_SIZE) / 2);
            lv_coord_t iy = (lv_coord_t)(s_m.dock_y + (s_m.dock_h - DOCK_ICON_SIZE) / 2);
            s_dock_cells[i] = build_icon(s_screen, i, ix, iy,
                                          DOCK_ICON_SIZE, DOCK_ICON_RADIUS, false,
                                          s_page_cap + i);
            s_dock_app[i] = i;
        }
    }

    // The home indicator is NOT built here — it lives on lv_layer_top() so it
    // persists over app windows (see build_home_button()), the way iOS's does.

    render_selection();
}

// ── Home button / indicator ─────────────────────────────────────────────────
// iOS's home indicator: a short, wide pill along the bottom edge, present on
// the home screen AND over every app. Built on lv_layer_top() rather than on
// the springboard, because that layer is composited above lv_scr_act()'s whole
// tree — which is exactly what "still reachable while an app is full-screen"
// requires, and the same trick the systemui module uses for its own chrome.
//
// Two objects, not one: the visible pill is deliberately tiny (4px tall), and
// a 4px touch target is unhittable on a resistive-feel panel with a finger. So
// an invisible, taller hit area carries the click and the pill is a passive
// child of it. Visual size therefore matches the design; usable size does not.
static lv_obj_t *s_home_btn;

#define HOME_PILL_H   4
#define HOME_HIT_H   18

// Set by the long-press handler so the CLICKED that follows the same press
// doesn't also fire Home — LVGL delivers LONG_PRESSED during the hold and
// CLICKED on release, so without this, opening the switcher would immediately
// be followed by going home and closing it again.
static bool s_home_longpressed = false;

static void home_btn_click_cb(lv_event_t *e)
{
    (void)e;
    if (s_home_longpressed) { s_home_longpressed = false; return; }

    // Recents counts as a screen to back out of first, matching how the same
    // gesture behaves on iOS — a tap while the switcher is up dismisses it
    // rather than falling through to the home screen underneath.
    if (purr_systemui_recents_open()) { purr_systemui_close_recents(); return; }

    // Hide whatever the foreground app has open and return to the springboard.
    // Routed through the window backend rather than done here because it also
    // has to clear the shown-window stack and restore focus.
    mochi_win_hide_foreground();
}

// Long-press the home bar to open the app switcher — iOS binds its switcher to
// a gesture on the home indicator, and with no nav bar there is no Recents
// button to press instead.
static void home_btn_longpress_cb(lv_event_t *e)
{
    (void)e;
    s_home_longpressed = true;
    purr_systemui_open_recents();
}

static void build_home_button(uint16_t w, uint16_t h)
{
    if (s_home_btn) return;   // built once; survives springboard rebuilds

    lv_coord_t pill_w = (lv_coord_t)(w / 3);

    s_home_btn = lv_obj_create(lv_layer_top());
    lv_obj_remove_style_all(s_home_btn);
    lv_obj_set_size(s_home_btn, pill_w, HOME_HIT_H);
    lv_obj_set_pos(s_home_btn, (lv_coord_t)((w - pill_w) / 2),
                                (lv_coord_t)(h - HOME_HIT_H));
    lv_obj_set_style_bg_opa(s_home_btn, LV_OPA_TRANSP, 0);
    lv_obj_clear_flag(s_home_btn, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_flag(s_home_btn, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(s_home_btn, home_btn_click_cb, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(s_home_btn, home_btn_longpress_cb, LV_EVENT_LONG_PRESSED, NULL);

    lv_obj_t *pill = lv_obj_create(s_home_btn);
    lv_obj_remove_style_all(pill);
    lv_obj_set_size(pill, pill_w, HOME_PILL_H);
    purr_fx_radius(pill, HOME_PILL_H / 2);
    lv_obj_set_style_bg_color(pill, COL_INDICATOR, 0);
    purr_systemui_fx_bg_opa(pill, LV_OPA_40);
    lv_obj_align(pill, LV_ALIGN_BOTTOM_MID, 0, -4);
    lv_obj_clear_flag(pill, LV_OBJ_FLAG_CLICKABLE);
}

// ── Actions ─────────────────────────────────────────────────────────────────

static void launch_app(int registry_idx)
{
    const app_entry_t *app = app_manager_get(registry_idx);
    if (!app) return;
    ESP_LOGI(TAG, "launching '%s' (idx=%d)", app->name, registry_idx);
    if (app->state == APP_STATE_RUNNING && app->window) {
        purr_win_show(app->window);
    } else {
        app_manager_launch_idx(registry_idx);
    }
    purr_systemui_enter_app(registry_idx);
}

static int sel_to_registry(int sel)
{
    if (SEL_IS_DOCK(sel)) {
        int slot = SEL_DOCK_SLOT(sel);
        if (slot < 0 || slot >= s_dock_slots) return -1;
        return s_dock_app[slot];
    }
    if (sel < 0 || sel >= s_page_cap) return -1;
    return s_grid_app[sel];
}

static void activate_selection(void)
{
    int idx = sel_to_registry(s_sel);
    if (idx >= 0) launch_app(idx);
}

// ── Touch swipe paging ──────────────────────────────────────────────────────
// Hand-rolled from PRESSED/PRESSING/RELEASED rather than LVGL's LV_EVENT_GESTURE.
// The gesture route was tried first and did not fire on hardware: LVGL only
// raises a gesture once its own velocity and distance thresholds are met on the
// object that took the press, and with the grid's icons covering most of the
// screen the press lands on a child that has its own click handling. Tracking
// the pointer directly is both deterministic and the same mechanism the system
// UI's panels already use for their vertical drag.
//
// Handlers are attached to the icons as well as the root, because a swipe that
// begins on an icon (i.e. almost every swipe, at this icon density) never
// reaches the root otherwise.
#define SWIPE_MIN_PX 36

static lv_coord_t s_touch_x0;
static bool       s_touch_down = false;

// True from the moment a swipe is recognised until the click it would
// otherwise produce has been swallowed — LVGL still delivers LV_EVENT_CLICKED
// on release, so without this every page swipe would also launch an app.
static bool s_swiping = false;

// Touch: move the cursor to whatever was tapped, then open it — so the touch
// and cursor models never disagree about what is selected.
static void cell_click_cb(lv_event_t *e)
{
    if (s_swiping) { s_swiping = false; return; }
    int sel = (int)(intptr_t)lv_event_get_user_data(e);
    s_sel = sel;
    render_selection();
    activate_selection();
}

static void set_page(int page)
{
    if (page < 0 || page >= s_page_count || page == s_page) return;
    s_page = page;
    // Keep the cursor on-screen after a page change; column is preserved so
    // paging feels like the content moving under a fixed cursor.
    if (!SEL_IS_DOCK(s_sel) && s_grid_app[s_sel] < 0) s_sel = 0;
    render_all();
}

// Grid movement. Down from the bottom row enters the dock, up from the dock
// returns to the bottom row, and horizontal motion past either edge pages.
static void move_cursor(int dcol, int drow)
{
    if (SEL_IS_DOCK(s_sel)) {
        int slot = SEL_DOCK_SLOT(s_sel);
        if (drow < 0) {
            // Back up into the last populated grid row, same column-ish.
            int last = -1;
            for (int i = 0; i < s_page_cap; i++) if (s_grid_app[i] >= 0) last = i;
            if (last >= 0) {
                int row = last / s_cols;
                int col = slot < s_cols ? slot : s_cols - 1;
                int cand = row * s_cols + col;
                if (cand > last) cand = last;
                s_sel = cand;
            }
        } else if (dcol != 0) {
            int n = 0;
            for (int i = 0; i < s_dock_slots; i++) if (s_dock_app[i] >= 0) n++;
            slot += dcol;
            if (slot < 0)  slot = 0;
            if (slot >= n) slot = n > 0 ? n - 1 : 0;
            s_sel = s_page_cap + slot;
        }
        render_selection();
        return;
    }

    int col = s_sel % s_cols;
    int row = s_sel / s_cols;

    if (drow > 0) {
        if (row + 1 < s_rows && s_grid_app[(row + 1) * s_cols + col] >= 0) {
            s_sel = (row + 1) * s_cols + col;
        } else {
            // Falling off the bottom of the grid drops into the dock.
            int n = 0;
            for (int i = 0; i < s_dock_slots; i++) if (s_dock_app[i] >= 0) n++;
            if (n > 0) s_sel = s_page_cap + (col < n ? col : n - 1);
        }
        render_selection();
        return;
    }
    if (drow < 0) {
        if (row > 0) s_sel = (row - 1) * s_cols + col;
        render_selection();
        return;
    }

    int next = col + dcol;
    if (next < 0) {
        if (s_page > 0) { set_page(s_page - 1); return; }
    } else if (next >= s_cols) {
        if (s_page + 1 < s_page_count) { set_page(s_page + 1); return; }
    } else {
        int cand = row * s_cols + next;
        if (s_grid_app[cand] >= 0) s_sel = cand;
    }
    render_selection();
}

// ── Input ───────────────────────────────────────────────────────────────────

static void sb_key_cb(lv_event_t *e)
{
    uint32_t key = lv_event_get_key(e);

    // Any keyboard/trackball input brings the selection ring back — it is
    // hidden while touch is driving (see s_cursor_visible). Done before the
    // switch so even a key that only activates still reveals what is selected.
    if (!s_cursor_visible) {
        s_cursor_visible = true;
        render_selection();
    }

    switch (key) {
        case LV_KEY_LEFT:  case LV_KEY_PREV: move_cursor(-1, 0); return;
        case LV_KEY_RIGHT: case LV_KEY_NEXT: move_cursor(+1, 0); return;
        case LV_KEY_UP:                       move_cursor(0, -1); return;
        case LV_KEY_DOWN:                     move_cursor(0, +1); return;
        case LV_KEY_ENTER:                    activate_selection(); return;
        case LV_KEY_ESC:                      set_page(0); return;
        default: break;
    }
}

// Touch swipe: attached to the root AND to every icon, so a swipe starting
// anywhere pages. Direction reads the way content moves under the finger —
// dragging LEFT pulls the next page in from the right.
//
// Touching at all hides the selection ring; see s_cursor_visible.
static void sb_touch_cb(lv_event_t *e)
{
    lv_event_code_t code = lv_event_get_code(e);
    lv_indev_t *indev = lv_indev_get_act();
    if (!indev) return;
    // Only pointer input drives this. The trackball and keyboard arrive as
    // keypad indevs and must not be mistaken for a touch, or they would hide
    // the very cursor they are trying to move.
    if (lv_indev_get_type(indev) != LV_INDEV_TYPE_POINTER) return;

    lv_point_t pt;
    lv_indev_get_point(indev, &pt);

    if (code == LV_EVENT_PRESSED) {
        s_touch_x0   = pt.x;
        s_touch_down = true;
        if (s_cursor_visible) {          // touch takes over: drop the ring
            s_cursor_visible = false;
            render_selection();
        }
    } else if (code == LV_EVENT_RELEASED) {
        if (!s_touch_down) return;
        s_touch_down = false;
        lv_coord_t dx = (lv_coord_t)(pt.x - s_touch_x0);
        if (dx <= -SWIPE_MIN_PX) {
            if (s_page + 1 < s_page_count) { s_swiping = true; set_page(s_page + 1); }
        } else if (dx >= SWIPE_MIN_PX) {
            if (s_page > 0)                { s_swiping = true; set_page(s_page - 1); }
        }
    }
}

static void attach_touch_handlers(lv_obj_t *obj)
{
    lv_obj_add_event_cb(obj, sb_touch_cb, LV_EVENT_PRESSED,  NULL);
    lv_obj_add_event_cb(obj, sb_touch_cb, LV_EVENT_RELEASED, NULL);
}

// ── Hosting the system UI ───────────────────────────────────────────────────

// Recents cards reuse the springboard's own per-app colour, so an app reads as
// the same colour in the switcher as on the home screen. `base` is ignored:
// the palette is fixed and saturated by design (see mochi_color_for_app()),
// and brightening it toward a caller-chosen floor would wash it out.
static lv_color_t mochi_tint_color(const char *name, uint8_t base)
{
    (void)base;
    return mochi_color_for_app(name);
}

// No app-drawer overlay in a springboard — the grid *is* the home screen —
// so "hide the drawer" just means return to the first page.
static void mochi_hide_drawer(void)
{
    set_page(0);
}

static const purr_systemui_host_t s_systemui_host = {
    .width                   = mochi_hal_width,
    .height                  = mochi_hal_height,
    .icon_for_app            = mochi_icon_for_app,
    .tint_color              = mochi_tint_color,
    .hide_drawer             = mochi_hide_drawer,
    .hide_foreground_windows = mochi_win_hide_foreground,
    .last_activity_ms        = mochi_hal_last_activity_ms,
    .wallpaper               = mochi_wallpaper,
    // iOS has no Back/Home/Recents row — Mochi draws a home indicator instead
    // and keeps every other systemui surface. See mochi.h.
    .suppress_navbar         = true,
    // Lets systemui's own login screen (systemui_login.c) join the same
    // group mochi_hal.c's keyboard/trackball indevs are bound to, so a
    // physical keyboard can type a password there too, not just tap.
    .group                   = mochi_hal_group,
};

// ── Public API ──────────────────────────────────────────────────────────────

void mochi_springboard_go_home(void)
{
    if (!s_screen) return;
    lv_obj_move_foreground(s_screen);

    // Tell the system UI we are back on the home screen. Nothing else does:
    // under the Android style this was the nav bar's Home button's job, and
    // Mochi suppresses that bar, so without this the status indicators stay
    // hidden forever after the first app launch — confirmed on hardware.
    purr_systemui_return_home();

    lv_group_t *g = mochi_hal_group();
    // No lv_group_set_editing() here: editing mode existed only to stop LVGL
    // swallowing an ENCODER's enc_diff as focus-stepping. The trackball is a
    // keypad emitting real arrow keys now (see mochi_hal.c's ball_read_cb),
    // and keypad input reaches the focused object regardless of edit mode.
    if (g) lv_group_focus_obj(s_screen);
}

void mochi_springboard_init(void)
{
    uint16_t w = mochi_hal_width();
    uint16_t h = mochi_hal_height();
    compute_metrics(w, h);

    s_screen = lv_obj_create(lv_scr_act());
    lv_obj_remove_style_all(s_screen);
    lv_obj_set_size(s_screen, w, h);
    lv_obj_set_pos(s_screen, 0, 0);
    // COL_BG stays as the base fill: it shows through if the wallpaper is a
    // different size than the panel, and is what the springboard falls back to
    // conceptually if the image is ever removed from the build.
    lv_obj_set_style_bg_color(s_screen, COL_BG, 0);
    lv_obj_set_style_bg_opa(s_screen, LV_OPA_COVER, 0);
    lv_obj_clear_flag(s_screen, LV_OBJ_FLAG_SCROLLABLE);

    // The wallpaper is created by render_all(), not here — see its comment.
    lv_obj_add_flag(s_screen, LV_OBJ_FLAG_CLICKABLE);
    lv_obj_add_event_cb(s_screen, sb_key_cb, LV_EVENT_KEY, NULL);
    attach_touch_handlers(s_screen);

    lv_group_t *g = mochi_hal_group();
    if (g) lv_group_add_obj(g, s_screen);

    recompute_pages();
    s_last_app_count = app_manager_count();
    render_all();

    // Status bar, drag-down panels, Recents and lock screen — the systemui
    // module, with its nav bar suppressed (see the host table above).
    purr_systemui_init(&s_systemui_host);

    // After systemui, so the home button is the last thing added to
    // lv_layer_top() and therefore sits above the status panels' own objects
    // rather than under them.
    build_home_button(w, h);

    mochi_springboard_go_home();   // focus + encoder edit mode

    ESP_LOGI(TAG, "springboard built (%ux%u, %d apps, %d page(s))",
             w, h, s_app_count, s_page_count);
}

void mochi_springboard_tick(void)
{
    purr_systemui_tick();

    int n = app_manager_count();
    if (n != s_last_app_count) {
        s_last_app_count = n;
        recompute_pages();
        render_all();
    }
}
