#!/usr/bin/env python3
"""Turn LVGL's public-domain Unscii 8 font (lv_font_unscii_8.c) into a fixed-cell C font.

    python gen_font.py <lv_font_unscii_8.c> <out.c>

Unscii is by Viznut and is in the public domain. Each glyph becomes one row-major cell,
8 pixels wide and CELL_H rows high, one byte per row with the leftmost pixel in bit 7.
Covers ASCII 0x20-0x7F.
"""

import re
import sys

LINE_HEIGHT = 9      # from the LVGL font: .line_height = 9, .base_line = 0
FIRST, COUNT = 0x20, 96


def parse(src):
    text = open(src, encoding="utf-8").read()
    bm = re.search(r"glyph_bitmap\[\]\s*=\s*\{(.*?)\};", text, re.S).group(1)
    bm = re.sub(r"/\*.*?\*/", "", bm, flags=re.S)
    data = [int(x, 16) for x in re.findall(r"0x[0-9a-fA-F]+", bm)]
    dsc = re.search(r"glyph_dsc\[\]\s*=\s*\{(.*?)\n\};", text, re.S).group(1)
    glyphs = []
    for m in re.finditer(r"\{\.bitmap_index = (\d+), \.adv_w = (\d+), \.box_w = (\d+), "
                         r"\.box_h = (\d+), \.ofs_x = (-?\d+), \.ofs_y = (-?\d+)\}", dsc):
        glyphs.append(tuple(int(x) for x in m.groups()))
    return data, glyphs


def render(data, g):
    idx, _adv, bw, bh, ox, oy = g
    rows = [[0] * 8 for _ in range(LINE_HEIGHT)]
    bit = idx * 8
    for y in range(bh):
        for x in range(bw):
            byte = data[bit // 8]
            on = (byte >> (7 - bit % 8)) & 1
            bit += 1
            px = ox + x
            py = LINE_HEIGHT - oy - bh + y      # baseline is the bottom of the line box
            if on and 0 <= px < 8 and 0 <= py < LINE_HEIGHT:
                rows[py][px] = 1
    return rows


def main():
    src, out = sys.argv[1], sys.argv[2]
    data, glyphs = parse(src)
    glyphs = glyphs[1:]                       # entry 0 is the reserved glyph
    assert len(glyphs) >= COUNT, len(glyphs)
    cells = [render(data, glyphs[i]) for i in range(COUNT)]

    used = [any(any(c[r]) for c in cells) for r in range(LINE_HEIGHT)]
    keep = [r for r in range(LINE_HEIGHT) if used[r]]
    lo, hi = keep[0], keep[-1]
    cell_h = hi - lo + 1
    print(f"rows used: {[int(u) for u in used]} -> cell height {cell_h}")

    lines = [
        "/* Generated by tools/gen_font.py from LVGL's lv_font_unscii_8.c.",
        " * Unscii is by Viznut, public domain. ASCII 0x20-0x7F, 8 wide, one byte per row,",
        " * leftmost pixel in bit 7. Do not edit by hand. */",
        '#include "purr_font.h"',
        "",
        f"const uint8_t purr_font_cell[{COUNT}][PURR_FONT_H] = {{",
    ]
    for i, c in enumerate(cells):
        rows = []
        for r in range(lo, hi + 1):
            v = 0
            for x in range(8):
                v |= c[r][x] << (7 - x)
            rows.append(f"0x{v:02X}")
        ch = chr(FIRST + i)
        label = ch if ch not in "\\*/" else f"0x{ord(ch):02X}"
        lines.append(f"    {{{', '.join(rows)}}},  /* {label} */")
    lines.append("};")
    open(out, "w", encoding="utf-8", newline="\n").write("\n".join(lines) + "\n")
    print(f"wrote {out}: {COUNT} glyphs, {cell_h} rows each")

    # Show a few letters so the result can be checked by eye.
    for ch in "AgQ@":
        print(f"'{ch}':")
        for r in range(lo, hi + 1):
            print("   " + "".join("#" if cells[ord(ch) - FIRST][r][x] else "." for x in range(8)))


if __name__ == "__main__":
    main()
