#!/usr/bin/env python3
"""
convert_wallpaper.py — Cupcake custom wallpaper converter

Resizes/crops any image to a target panel resolution and writes a raw
RGB565 pixel file. Copy the output onto the device's SD card under
/wallpapers/, then pick it in Settings -> Wallpaper.

This does NOT get compiled into firmware or go through convert_icons.py's
pipeline — Cupcake loads it at runtime straight off the SD card via
fopen/fread, so there's no C-array step and no rebuild needed to add or
change a wallpaper.

Usage:
  python3 convert_wallpaper.py photo.jpg beach.rgb565
  python3 convert_wallpaper.py photo.jpg beach.rgb565 --width 320 --height 240
  python3 convert_wallpaper.py photo.jpg beach.rgb565 --swap   # for boards
                                                                # with CONFIG_LV_COLOR_16_SWAP=y

Dependencies: Pillow
  pip3 install Pillow
"""

import argparse
import struct
import sys

from PIL import Image, ImageOps


def to_rgb565(in_path, width, height, swap):
    """Resize/crop to the panel and return raw RGB565 bytes."""
    img = Image.open(in_path).convert("RGB")
    img = ImageOps.fit(img, (width, height), Image.LANCZOS)

    out = bytearray(width * height * 2)
    pixels = img.load()
    i = 0
    for y in range(height):
        for x in range(width):
            r, g, b = pixels[x, y]
            rgb565 = ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)
            if swap:
                out[i]     = (rgb565 >> 8) & 0xFF
                out[i + 1] = rgb565 & 0xFF
            else:
                out[i]     = rgb565 & 0xFF
                out[i + 1] = (rgb565 >> 8) & 0xFF
            i += 2
    return out


def convert(in_path, out_path, width, height, swap):
    out = to_rgb565(in_path, width, height, swap)
    with open(out_path, "wb") as f:
        f.write(out)

    print(f"wrote {out_path}  ({width}x{height}, {len(out)} bytes, "
          f"{'swapped' if swap else 'native'} byte order)")
    print(f"copy this file to the SD card's /wallpapers/ folder, then pick it "
          f"in Settings -> Wallpaper on the device.")


def convert_c(in_path, out_path, width, height, swap, symbol):
    """
    Emit an LVGL lv_img_dsc_t as C, for a wallpaper compiled INTO the firmware
    rather than loaded off SPIFFS/SD at runtime.

    Why both paths exist: the raw .rgb565 above is the user-supplied wallpaper
    story (drop a file on the SD card, pick it in Settings, no rebuild). This
    one is the OS's own default — it has to be there on a freshly-erased device
    with no SD card and an empty SPIFFS, which a runtime-loaded file cannot
    guarantee.

    Format is LV_IMG_CF_TRUE_COLOR at LV_COLOR_DEPTH=16: 2 bytes per pixel, no
    alpha. Byte order MUST match the build's LV_COLOR_16_SWAP setting — pass
    --swap only for boards that set CONFIG_LV_COLOR_16_SWAP=y. Getting this
    wrong does not fail to build, it just renders the image with mangled
    colours, so check the device's config rather than copying another board's
    invocation.
    """
    data = to_rgb565(in_path, width, height, swap)

    lines = [
        f"// {symbol} — {width}x{height} RGB565 wallpaper, "
        f"{'swapped' if swap else 'native'} byte order",
        "// Auto-generated by convert_wallpaper.py --c-array — do not edit.",
        "//",
        "// Compiled into the firmware so a freshly-erased device with no SD",
        "// card still has a wallpaper. Runtime-selectable wallpapers are a",
        "// separate path — see this script's convert() and the Settings app.",
        "",
        '#include "lvgl.h"',
        "",
        f"static const uint8_t {symbol}_data[] = {{",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join(f"0x{b:02X}" for b in chunk) + ",")
    lines += [
        "};",
        "",
        f"const lv_img_dsc_t {symbol} = {{",
        "    .header = {",
        "        .cf          = LV_IMG_CF_TRUE_COLOR,",
        "        .always_zero = 0,",
        "        .reserved    = 0,",
        f"        .w           = {width},",
        f"        .h           = {height},",
        "    },",
        f"    .data_size = {len(data)},",
        f"    .data      = {symbol}_data,",
        "};",
        "",
    ]

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))

    print(f"wrote {out_path}  ({width}x{height}, {len(data)} bytes of pixel data, "
          f"{'swapped' if swap else 'native'} byte order)")
    print(f"declare it with:  extern const lv_img_dsc_t {symbol};")


def main():
    parser = argparse.ArgumentParser(
        prog="convert_wallpaper",
        description="Convert an image to a raw RGB565 wallpaper file for Cupcake",
    )
    parser.add_argument("input", help="source image (jpg/png/etc)")
    parser.add_argument("output", help="output .rgb565 file")
    parser.add_argument("--width", type=int, default=320, help="panel width (default 320)")
    parser.add_argument("--height", type=int, default=240, help="panel height (default 240)")
    parser.add_argument("--swap", action="store_true",
                         help="byte-swap each pixel — needed on boards built with "
                              "CONFIG_LV_COLOR_16_SWAP=y (check the device's "
                              "generated sdkconfig; if the symbol is absent, "
                              "swap is OFF and you must not pass this)")
    parser.add_argument("--c-array", action="store_true",
                         help="emit an LVGL lv_img_dsc_t .c file compiled into "
                              "firmware, instead of a raw .rgb565 for SD/SPIFFS")
    parser.add_argument("--symbol", default="purr_wallpaper",
                         help="C symbol name for --c-array (default purr_wallpaper)")
    args = parser.parse_args()

    try:
        if args.c_array:
            convert_c(args.input, args.output, args.width, args.height,
                      args.swap, args.symbol)
        else:
            convert(args.input, args.output, args.width, args.height, args.swap)
    except FileNotFoundError:
        print(f"error: could not open '{args.input}'", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
