idf_component_register(SRCS "src/purr_util.c" "src/purr_decision.c" "src/purr_keybag.c"
                            "src/purr_cfg.c" "src/purr_verify.c" "src/purr_menu.c"
                            "src/purr_term.c" "src/purr_cli.c" "src/purr_wifi.c" "src/purr_manifest.c"
                       INCLUDE_DIRS "include")
