/* purr_font.h - the built-in 8x8 font (ASCII 0x20-0x7F), generated by tools/gen_font.py. */
#ifndef PURR_FONT_H
#define PURR_FONT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

#define PURR_FONT_W      8
#define PURR_FONT_H      8
#define PURR_FONT_FIRST  0x20
#define PURR_FONT_COUNT  96

/* One byte per row, leftmost pixel in bit 7. */
extern const uint8_t purr_font_cell[PURR_FONT_COUNT][PURR_FONT_H];

/* The glyph for a character. Anything outside the font shows as '?'. */
static inline const uint8_t *purr_font_glyph(char c)
{
    unsigned i = (unsigned char)c;
    if (i < PURR_FONT_FIRST || i >= PURR_FONT_FIRST + PURR_FONT_COUNT) {
        i = '?';
    }
    return purr_font_cell[i - PURR_FONT_FIRST];
}

#ifdef __cplusplus
}
#endif

#endif /* PURR_FONT_H */
